services:
  web:
    build: .
    command: /bin/bash -c "uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:00"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true