services:
  web:
    build: .
    command: /bin/bash -c "/wait-for-it.sh db-1:5432 -- uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 5 && chromium --no-sandbox --kiosk http://localhost:8000"
    ports:
      - "8000:8000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    environment:
      - DISPLAY=${DISPLAY}
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
