services:
  web:
    build: .
    command: /bin/bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 5 && chromium --no-sandbox --kiosk http://localhost:8000"
    ports:
      - "8000:8000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
