services:
  kivy_app:
    build: .
    container_name: kivy_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Для передачи X11 сокета
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/spidev0.0:/dev/spidev0.0"
    privileged: true                    # Для доступа к устройствам
    command: python main.py



